//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiRest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Emociones_Sesion
    {
        public System.Guid id { get; set; }
        public Nullable<System.Guid> sesionId { get; set; }
        public string etiqueta { get; set; }
        public byte[] tiempo { get; set; }
        public string fotografia { get; set; }
    
        public virtual Sesion Sesion { get; set; }
    }
}
