//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiRest.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class megacodeEntities : DbContext
    {
        public megacodeEntities()
            : base("name=megacodeEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Conexion> Conexion { get; set; }
        public virtual DbSet<Emociones_Sesion> Emociones_Sesion { get; set; }
        public virtual DbSet<Nivel> Nivel { get; set; }
        public virtual DbSet<Niveles_Terminados> Niveles_Terminados { get; set; }
        public virtual DbSet<Usuario> Usuario { get; set; }
        public virtual DbSet<ConexionSesion> ConexionSesion { get; set; }
        public virtual DbSet<Sesion> Sesion { get; set; }
        public virtual DbSet<TipoNivel> TipoNivel { get; set; }
    
        [DbFunction("megacodeEntities", "obtenerMarcadorUsuario")]
        public virtual IQueryable<obtenerMarcadorUsuario_Result1> obtenerMarcadorUsuario(Nullable<long> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<obtenerMarcadorUsuario_Result1>("[megacodeEntities].[obtenerMarcadorUsuario](@id)", idParameter);
        }
    }
}
