//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiRest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Nivel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Nivel()
        {
            this.Niveles_Terminados = new HashSet<Niveles_Terminados>();
            this.Sesion = new HashSet<Sesion>();
        }
    
        public int id { get; set; }
        public string nombre { get; set; }
        public string ruta { get; set; }
        public int comandos { get; set; }
        public int si { get; set; }
        public int para { get; set; }
        public int mientras { get; set; }
        public int dificultad { get; set; }
        public int grupo { get; set; }
        public short tipoNivel { get; set; }
        public string cadenaOptima { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Niveles_Terminados> Niveles_Terminados { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sesion> Sesion { get; set; }
        public virtual TipoNivel TipoNivel1 { get; set; }
    }
}
